### ISSUE TITLE
"-auto" option as an alternative to  `@additional_keys`? (updated)

### ISSUE THREAD

**Issue by oodler577** [haukex/Util-H2O#1]
HI, I would find it majorly helpful if there was a `-noop` option for keys that are undefined, as an alternative to providing a list of keys to include that do not exist in the hashref via ` @additional_keys`.

The use case I have in mind is one where the hash keys are not guaranteed to exist, but perhaps I might be calling them anyway and I wish them to simply return `undef` (or some default value) so I can check rather there be an error that the `sub` is undefined - or worse (for me) - have to us `can`.

Example use would be:

```
my $hashref = { foo => 1, bar => 2 };
h2o -noop, $hashref;
foreach my $func (qw/foo bar baz/) {
  if (my $val = $hashref->$func) {
    print qq{Woot! $val\n};
  }
}
```

or to define a default return:

```
my $hashref = { foo => 1, bar => 2 };
h2o -noop=>q{}, $hashref;
foreach my $func (qw/foo bar baz/) {
  print qq$func contains, '$val'\n};
}
```

If you're open to such a feature, I am happy to attempt to implement; but the code is so tight I am not sure I could match its conciseness. SImilarly, I am only suggesting `-noop` to demonstrate the merits of this request, since it seems to me it'd amount to a "no op". I am happy to assist in any case, please just let me know if you'd consider this and if you'd like me to submit a PR.

**Comment by oodler577** [comment]
I suppose the idea would need to be consistent with the idea of providing a setter; i.e., if it's just used to _get_ the value; there the default value can always be used and no subroutine symbol would need to be defined. Upon first "set", that would need to change. Not sure what to suggest, but this request is not necessarily just for detecting and returning some default value for an unanticipated key. On the otherhand, it might be desirable to respect a "get" but die if used in this manner as a setter. Thoughts? Happy to flesh this idea out with you.

**Comment by oodler577** [comment]
Any thoughts, 2 places this is helpful are with things that might not be know _a priori_ - e.g., anything based on DBI's `fetchall_arrayref` with `{ Slice => {} }`.

**Comment by haukex** [comment]
Thanks for the idea! Do I understand correctly that in your first example, you'd want `$hashref->$func` with `$func` being `"baz"` to return `undef` and in the second example it would return `""`?

This feature could only be implemented with autoloading, so I'd be inclined to call the option `-auto` and allow the user to pass a coderef for the method that would get called. This would mean that your first example would look like `h2o -auto=>sub{}, $hashref;` and your second one `h2o -auto=>sub{""}, $hashref;` (due to the way options are handled I can't have an option that either takes a value or doesn't).

**Comment by haukex** [comment]
Thinking about this some more: On the one hand, it's of course possible for me to extend this idea further, for example adding a `-dflt` option for default return values, or I could make autoloaded setters, and so on. However, on the other hand, part of the reason of turning a hash into an object in the first place is that one gets typo protection on the method calls. Adding autoloading removes that protection again, e.g. autoloaded setters wouldn't make the object much different from a hash, so I think the `-auto` option is as far as I'd want to go at the moment...

**Comment by oodler577** [comment]
@haukex I think `-auto` would be a perfect complement to what's here already. I am glad you like the idea. I've been using it for other things, and the only "missing feature" I keep running into is the need for something like `-auto` - and yes, you have my examples of use correct. Please let me know how I can assist. Cheers...

**Comment by oodler577** [comment]
I updated the title of this issue to reflect your preference for `-auto`, which I agree is a superior idea.

**Comment by haukex** [comment]
Thanks! Implementing this shouldn't be too difficult I think, I'll take a closer look at it in the next week or two.

**Comment by haukex** [comment]
In looking at the implementation of this, I realized that it's actually already possible to implement your two examples with the current version of the module. Simply adding a key `AUTOLOAD` to the hashref causes this to become the "catch-all" for any undefined methods. This means that your first case would simply be:
```
use Util::H2O;
use Data::Dump;
my $hashref = { foo => 1, bar => 2 };
h2o $hashref, 'AUTOLOAD';
for my $func (qw/foo bar baz/) {
  dd $func, $hashref->$func;
}
```
and your second case:
```
my $hashref = { foo => 1, bar => 2, AUTOLOAD=>'' };
h2o $hashref;
```
This is because putting a key `AUTOLOAD` in the hashref causes a getter/setter to be installed in the package with the name `AUTOLOAD`, which Perl then automatically uses as such.

It's also possible to use `-meth` with a value `AUTOLOAD => sub {...}` in the hashref to install a completely custom `AUTOLOAD`.

The only advantage I still see in implementing an `-auto` option would be that installing a custom `AUTOLOAD` would not require the user to turn on `-meth`. I'm still considering whether that's worth it...

**Comment by haukex** [comment]
After some more deliberation, I've decided not to implement `-auto`, instead just documenting `AUTOLOAD`ing in the next release. The main reasons are what I mentioned earlier: a major motivation for this module is to provide protection against typos by using method calls instead of hash keys, which is an argument against adding an explicit option. And for anyone wanting to add autoloaded methods, this is already possible with the existing features. Thank you very much for raising this issue, as I hadn't thought about autoloading previously, and it's good to get it tested and documented.

**Comment by oodler577** [comment]
This is great disovery, thank you!

**Comment by oodler577** [comment]
It occurs to me, this could also apply to `DESTROY` - any other normal default methods called if they exist related to `bless`ed things? I suppose another could be `TO_JSON` for use with the `JSON` family of modules.
