### ISSUE TITLE
hash keys with spaces

### ISSUE THREAD

**Issue by oodler577** [haukex/Util-H2O#10]
I have some CSV that I am parsing with `Text::CSV`; `h2o` would be ideal with dealing with these records. Unfortunately, the field names have spaces. `h2o` deals with this fine, but then I am unsure how or if I can call the accessors.

I confirmed via the symbol table (which required some creativity on my part to get at) that subroutines were indeed being added to the symbol table with spaces in their names. This request is 2 fold:

1. `h2o` should warn if keys have spaces, unless passed an option like `-add-underscores` (or something like that to make the accessors callable subnames), which I can see useful in the case that the keys either start with a number (prepend with `_`) or have spaces (replace `\s+` with `_`)

2. would be super handly to have an introspection util function that dumped the symbol table; here's what I did to get at it ( I am sure there's another, better way to do it):

```
        h2o $record;
        my $rec_ns = ref $record;
        my $dd = q{print Data::Dumper::Dumper(%} . $rec_ns . q{::)};
        eval $dd;
```

**Comment by oodler577** [comment]
Quick hack to add underscores to my hash reference; it's destructive but for my purpose it's okay. Each record is a result from `my $aoh = Text::CSV->new(in => $file, headers => 'auto');` - I iterate over the array of hashes it returns (1 for each record), and apply `h2o` to each record as I process it.
```
# replace spaces with underscores
sub _fix_fields_for_h2o {
    my ($self, $hashref) = @_;
    foreach my $oldkey (keys %$hashref) {
      my $newkey = $oldkey;
      $newkey =~ s/\s+/_/g;
      $hashref->{$newkey} = $hashref->{$oldkey};
      delete $hashref->{$oldkey};
    }
    return $hashref;
}
```

**Comment by oodler577** [comment]
I discovered this neat header munching hook in `Text::CSV::csv` that allowed me to head off the spaces in the column names. However, this may be a useful thing for `h2o` regardless.

**Comment by haukex** [comment]
Thanks, I think an option to transform keys in the hash, similar to Text::CSV's headers option, would be a good addition! It would also be possible to add a warning if some keys in the hash won't be callable as method names.

As for your other questions:

> I am unsure how or if I can call the accessors.

See [Method Call Variations](https://perldoc.perl.org/perlobj#Method-Call-Variations)

> would be super handly to have an introspection util function that dumped the symbol table

Dumping the symbol table is not really trivial and not something I would recommend at all unless debugging, because Perl's symbol table is populated with all kinds of things that don't necessarily "make sense" unless you know about the internals. If you really wanted to, you could use [Devel::Symdump](https://metacpan.org/pod/Devel::Symdump), but once again my recommendation here is to look at the original hash before you use `h2o` on it, or keeping around a shallow copy of the hash to inspect.

I'll have to think about whether it is possible in a reasonable way to keep a list of method names after transformation, though I'm still a bit unsure of the use case for this?

I'm not sure if it shows up in your notifications when I @ mention you - have a look at #9 as well!

**Comment by oodler577** [comment]
I agree, the only reason I dumped the symbol table was to see what `h2o` did with the keys. If we could optionally "munge" the keys to make sure they're callable (or `warn`) would be great. Outside of that, short of modifying the underlying keys themselves, it might be prudent to simply keep a mapping and some sort of specially method that would allow this to work:

```
h2o $my_hashref;
foreach my $key (keys %$my_hashref) {
  my $meth = $my_hashref->_call_with($key);
  say $my_hashref->$meth;
}
```

Not related - I've also been wondering about some useful things for managing nested structures and the accessors generated with `-recurse`; but so far I have not had the need to really be picky about anything beyond the first level of hash keys.

**Comment by oodler577** [comment]
>  - key and method names should generally be known beforehand, otherwise using this module doesn't make too much sense to me.

I agree, it was just a thought in the event there might have been an objection of "losing" info, but like you said if it's deterministic then they can easily be transformed back.

**Comment by haukex** [comment]
So I was thinking about this, and I feel like the spirit of the module is much like that of the `*::Tiny` namespace: see the replies in the thread "[*::Tiny modules namespace origins](https://www.perlmonks.org/?replies=1;node_id=11122599;displaytype=print)". That means that instead of pulling more and more functionality into the module, which makes the code and especially tests complex, a philosophy of "do one thing and do it well" is better. Some things make sense to do inside the module, but similar to what I wrote over in #7 about not wanting to reinvent the `Hash::Merge` and `Role::Tiny` wheels, I think rewriting a hash is actually better done outside the module. So in this case I've decided to show how to do so in the "Cookbook" instead of implementing a new option.
