### ISSUE TITLE
`h2o` and Dancer2 `session`

### ISSUE THREAD

**Issue by oodler577** [haukex/Util-H2O#13]
I ran into an issue when using file based sessions in Dancer2. Hopefully you're familier. Basically, I have it set up to write to a YAML file:

```
  my $h2o_ref = h2o { herp => 1 }, qw/foo bar baz/;
  ...
  session MYVAR = $h2o_ref;
```

Then later, I need to get `$h2o_ref` back in another scope:

```
  my $h2o_ref = session 'MYVAR';

  #... all accessors are "lost"
```

Why is this? Here's why; the YAML session backend looks like:

```
---
MYVAR: Util::H2O::_r4ndomhAsH
  herp: 1
```

So, while this obviously doesn't encode a symbol table that it temporal, there is no "real" module, `Util::H2O::_r4ndomhAsH`. It's not because of the `_r4ndomhAsH` part, it could just be that something set via `-classify` doesn't exist either.

Anyway, the ultimate problem is that the _in flight_ object doesn't survive serialization. This could be invoked in other ways (e.g., `encode_json`, etc). But since it's in the same Dancer2 app session it might be overlooked.

My solution was pretty simple: _don't write_ `h2o` references to a Dancer2 session.

Instead, I ended up using `Util::H2O::More::o2h`:

```
  use Util::H2O::More qw/o2h/;
  my $h2o_ref = h2o { herp => 1 }, qw/foo bar baz/;
  ...
  session MYVAR = o2h $h2o_ref;
```

Then later, I need to get `$h2o_ref` back in another scope:

```
  my $h2o_ref = h2o session 'MYVAR', qw/foo bar baz/;

  #... now accessors are "found"
```

I am creating this just to point out one other "gotcha" I've hit. But also to note that `o2h` is helpful here, particularly, `o2h -recurse`. But do you have any suggestions or can you think of any cleaner ways to avoid this?

**Comment by haukex** [comment]
Thanks for this, I do think that implementing `o2h` in `Util::H2O` makes sense. I would default it to being recursive, since the non-recursive version is simply `{%$h2o}`.

**Comment by oodler577** [comment]
Great! In retrospect, I wish I had added to `Util::H2O::o2h` the ability to convert default accessors that might not yet have underlying hashkeys as existing (undefined) hash keys. E.g.,

```
my $h2o_ref = h2o { qux => 1 }, qw/foo bar baz/;

my $o2h_ref = o2h $h2o_ref;

```

`$o2h_ref` should look like:

```
{
  foo => undef,
  bar => undef,
  baz => undef,
  qux => 1,
}
```

And I am more than happy to "deprecate" `Util::H2O::o2h` in lieu of main module support.

Also, the "recursive" by default case is indeed the right call, besides your point if it works for an N-deep structure, it should work for a hash with just one level of keys =-)

**Comment by haukex** [comment]
> ... the ability to convert default accessors that might not yet have underlying hashkeys as existing (undefined) hash keys.

This is problematic due to `h2o` not keeping "meta" information around (similar to what we discussed in #10) - if a hash key doesn't exist, then the only way to know that it might once have existed is to either look at the original hash, or to look into the symbol table, the latter of which has its own significant problems.

Instead of the code you wrote above, you might consider giving each of the `@additional_keys` a default value of `undef` to make sure the keys exist in the underlying hash with something like:
```perl
my $h2o_ref = h2o { map({($_=>undef)} qw/foo bar baz/), qux => 1 };
```

> One other "question" I had to face was, does `o2h` edit "in place" or return?

This goes back to the discussion we had over in #4: Changing the `bless`ing of an object is problematic because it causes destructors to not be called. So my `o2h` implementation makes shallow copies of each `h2o` object.

To respond to your questions in the first comment:

> all accessors are "lost" ... Why is this?

As you said, symbol table information is typically not stored when serializing. It was the call to `h2o` that set up the `sub`s in the `Util::H2O::_r4ndomhAsH` package, but when an object is serialized, normally only its underlying hash and the class it was`bless`ed into are stored, similar to what you showed, and when it is retrieved there isn't really a good way to know what the call to `h2o` looked like to be able to set up the package the way it looked before serialization. So the correct solution is what you wrote:

> don't write `h2o` references to a Dancer2 session.
