### ISSUE TITLE
need an option to turn on implicit cloning

### ISSUE THREAD

**Issue by XSven** [haukex/Util-H2O#23]
I  wanted to use `Util::H2O` to create an immutable object that represents `%ENV`:

```
perl -MUtil::H2O -e '
  my $env = h2o( -class => "Env", -ro, \%ENV );
  local $ENV{HOME} = "/home/foo"
'
Modification of a read-only value attempted at -e line 3.
```
I need an `h2o` option that although I am passing `\%ENV` implicitly uses` { %ENV }` or even better a deep clone so that the above `local` change of `%ENV` does not raise a **Modification of a read-only value attempted** exception.

**Comment by haukex** [comment]
Hi, thanks for the feedback, though I think I don't yet understand your use case. The *"Modification of a read-only value attempted"* error you're getting is due to the `-ro` option, i.e. you explicitly asked for the entire `%ENV` hash to be locked. If on the other hand you want to create an object from a read-only clone of `%ENV`, what's wrong with writing `h2o -ro, {%ENV}`? I don't really see the need for an extra option for that. As far as I can remember, `%ENV` should be a mapping of strings to strings, so a deep clone shouldn't be necessary. And even if it were, there are plenty of modules on the CPAN for that... I'd like to keep this module to "do one thing and do it well", so I currently don't see the necessity to implement cloning in this module.

**Comment by XSven** [comment]
> ... what's wrong with writing h2o -ro, {%ENV}?

Nothing is wrong with that and yes deep cloning isn't necessary for `%ENV`. But from my perspective a `-clone` option would increase the readability. I accept the point

> I'd like to keep this module to "do one thing and do it well", so I currently don't see the necessity to implement cloning in this module.
