### ISSUE TITLE
make creating subclasses easier

### ISSUE THREAD

**Issue by XSven** [haukex/Util-H2O#24]
```
perl -MUtil::H2O -E '
  my $env = h2o( -class => "Env", -ro, { %ENV } );
  $ENV{NAME} = "Fred";
  my $env1 = h2o( -class => "Env", -ro, { %ENV } );
  say $env->NAME;
  say $env1->NAME
  ;
'
Subroutine ... redefined at ...
Subroutine ... redefined at ...

Fred
```
The above one-liner **should fail** at the line

`say $env->NAME;`

with the message

**Can't locate object method "NAME" via package "Env" at**

This doesn't happen because the creation of `$env1` has an impact on `$env`. The problem is that they are referring to the same class/package name `Env`. This is on purpose because I wanted to create objects of the same class! The problem is that `Util::H2O` does not really create **per-object accessors** in the way it is done by `Object::Accessor`. Could this be fixed or amended?!

**Comment by haukex** [comment]
Hi,

> The problem is that they are referring to the same class/package name `Env`. This is on purpose because I wanted to create objects of the same class!

This is the expected behavior and is [documented](https://metacpan.org/pod/Util::H2O#-class-=%3E-classname) as such. *Every* call to `h2o` installs methods into the symbol table, and if you're using the `-class` option, every call to `h2o` is like defining a `package`, so there really only should be one call to `h2o` for every value of `-class`. See the documentation for details and alternatives.

Like in #23, I'm a bit confused as to what your use case is here. If you want to create an *immutable* object from `%ENV`, why do you need two of them, why isn't one enough? And why do they both need to be of the class `Env`?

**Comment by haukex** [comment]
> If the creation of `$env1` impacts the behaviour of `$env` this means that `$env` wasn't really immutable.

To be a bit nitpicky: `-ro` does make the underlying hash completely immutable. And your code example above can be modified to prove this: both `$env->NAME('anything')` and `$env1->NAME('anything')` throw an error without modifying the hash.

`h2o` modifies the *package*, not the object that is blessed into that package\*. This is not really a "normal" operation to do, which is why `h2o` normally uses unique `package`s. Taking that into consideration, the unusual thing you're asking `h2o` to do here is create two `packages` with the same name and different methods, which is why you're getting the "redefined" warnings as a hint that something is wrong.

(\* Of course with a few exceptions, e.g. `-meth` can remove keys from the hash.)

> But if I want to make sure that my `$env` is still up to date I want to be able to create a second one `$env1` that represents the current state of `%ENV`.

Do both objects need to exist in parallel? Because if not, then note that you *could* turn the `-clean` option back on, then, when all references to `$env` go away, the `Env` package is deleted, and you're free to re-use that package name for `$env1`. However, in comparison to the different options I've suggested, personally I'd probably use one of the others.

> Changing the classname to overcome this, isn't an option for me.

I am curious why? Note the documentation mentions the use of `-isa`, so for example `-class => sprintf('Env::_%x', $hash+0), -isa => 'Env'` would mean that the two objects would simply look like subclasses of `Env` and therefore pass any type checks for `Env` objects etc. And since the two classes might have different methods (like in your example above), the differentiation would make sense.

Anyway, since you closed the issue, what solution did you end up going with?

**Comment by XSven** [comment]
Thanks for the `-isa` option hint. This
```perl
perl -MUtil::H2O -E '
  my $hash = { %ENV };
  my @opts = ( -ro, -isa => "Env", -class => sprintf("Env::_%x", $hash+0) );
  my $env = h2o @opts, $hash;
  $ENV{NAME} = "Fred";
  $hash = { %ENV };
  @opts = ( -ro, -isa => "Env", -class => sprintf("Env::_%x", $hash+0) );
  my $env1 = h2o @opts, $hash;
  say $env->NAME;
  say $env1->NAME;
'
Can't locate object method "NAME" via package "Env::_110145a80" at -e line 9.

```
works as expected. But its really cumbersome. I am looking for a per-object accessor module like `Object::Accessor` but with
[read-only accessors](https://metacpan.org/pod/Object::Accessor#TODO). It seems that `Util::H2O` offers a similar functionality using dynamically generated package names that overwrite eachother if they are made static.

**Comment by haukex** [comment]
Reopening this because I think a `-subclass => 'Foo'` option that is the equivalent of `-isa => 'Foo', -class => sprintf("Foo::_%x", $hash+0)` should be fairly easy to implement.

**Comment by haukex** [comment]
I decided on a `-parent` option instead. Once I release v0.26, you'll be able to write your example code like this:

````perl
my $env = h2o -ro, -parent, -class=>"Env", {%ENV};
$ENV{NAME} = "Fred";
my $env1 = h2o -ro, -parent, -class=>"Env", {%ENV};
say $env1->NAME;  # "Fred"
say $env->NAME;   # Can't locate object method "NAME" via package "Env::_609797c7c568"
````

**Comment by haukex** [comment]
@XSven I also just pushed a new experimental module, `Util::H2O::Also`, that is basically a simple reimplementation of the basics of `Object::Accessor`. I assume this is the kind of thing you were after?

````perl
use Util::H2O::Also;
@Env::ISA = ('Util::H2O::Also');
my $env = Env->new(-ro, {%ENV});
$ENV{NAME} = "Fred";
my $env1 = Env->new(-ro, {%ENV});
say $env1->NAME;  # "Fred"
say $env->NAME;   # Can't locate object method "NAME" via package "Env"
````

**Comment by XSven** [comment]
Your initial idea (`-subclass => 'Foo'`) refers to an option that has an argument. The revised idea (`-parent`) uses a flag. I would prefer the option with argument syntax

`my $env = h2o -ro, -parent => 'Env', {%ENV};`

because `-class` should always refer to the class name into which the object is blessed.

**Comment by XSven** [comment]
I do not see the need to have yet another redundant(?!) CPAN module (`Util::H2O::Also`). Unfortunately I didn't find the time yet to get co-maintainer of `Object::Accessor`. I would prefer an approach that amends `Object::Accessor`.

**Comment by haukex** [comment]
> I would prefer the option with argument syntax

The reason I didn't do that was that the options processing in the module is already extremely complex as it is. Consider for example the case where someone is using `-classify => {...}`, now they would have to write `-meth, -new, -parent => 'Classname', {...}`, unless I provided the same level of complexity as `-class` and `-classify`. But I will take your comment into consideration and think about it one more time before I publish.

> because `-class` should always refer to the class name into which the object is blessed.

I understand what you mean, but this is actually the other reason I went with a flag option - after considering it, I think I have seen more problems with people misunderstanding how the `-class` option works than useful uses, so I don't think `-parent` amending its meaning is a big problem. I actually slightly regret providing `-classify`, since IMHO writing simple class definitions is probably better left to modules like `Class::Tiny` or `Moo`.

> I do not see the need to have yet another redundant(?!) CPAN module

That's why the module is clearly marked as **experimental** - I did it for fun and as a test. My module does have some very minor advantages over `Object::Accessor`, for example, every method call (including e.g. `new` and `VERSION`) except for `isa` and `can` are passed to the hash.
