### ISSUE TITLE
More concise idiom for name-spaced recursive accessors via `-recurse`

### ISSUE THREAD

**Issue by oodler577** [haukex/Util-H2O#3]
I love this module more every time I use it. I ran into this situation, and wanted to just ask if there was a better way to do it; there may not be and I am okay with that. I like it becuase it's simple and powerful.

Here's my situation, I have a nested hash that I want to provide deep accessors.

```
my $x = {
    foo  => 'bar',
    baz  => 'herp',
    deep => {
        a => 1,
        b => 2
    }
};

h20 -recurse,-classify => q{My::Class}, $x
```

Which created,

```
$VAR1 = bless( {
                 'deep' => bless( {
                                    'b' => 2,
                                    'a' => 1
                                  }, 'Util::H2O::_800ade810' ),
                 'baz' => 'herp',
                 'foo' => 'bar'
               }, 'My::Class' );
```

What I want is a way to replicate this effect,

```
my $x = {
    foo  => 'bar',
    baz  => 'herp',
    deep => {
        a => 1,
        b => 2
    }
};
h20 -classify => q{My::Class}, $x;
h20 -classify => q{My::Class::Details}, $x->deep
```

Which results in,

```
$VAR1 = bless( {
                 'deep' => bless( {
                                    'a' => 1,
                                    'b' => 2
                                  }, 'My::Class::Details' ),
                 'baz' => 'herp',
                 'foo' => 'bar'
               }, 'My::Class' )
```

Now, due to the arbitrary nature of nested data structures I don't see a clean way to do this. So I submit this to you in case it inspires something for you. Otherwise, like I said, it's not a big deal - the power in `h2o`'s simplicity is too great to corrupt with a capability that has such a simple work around (at least in this limited use case)

**Comment by haukex** [comment]
Glad to hear you like it!

I purposely limited what `-recurse` passes down because it gets very complicated quickly. For example, even if I were to be able to specify something like "keys named `deep` should be cast to `My::Class::Details`", what is supposed to happen if the nested hash contains a key named `deep` too, or if the key `deep` isn't a hashref? And if I pass `-classify` down to nested hashes, that means it would also make sense to pass down `-meth`, `-class`, `-new`, `-isa`, `-destroy`, `-clean` ... I don't really want to think about how complex it would be to specify each of those options for each of the nested hashes, and write tests for all that 🙃

This module is really only meant for "quick and dirty" solutions, and at some level of complexity it really does become better to use something like [Moo](https://metacpan.org/pod/Moo), which is still pretty lightweight and easy to use.

I think it's also noteworthy that I see different approaches to using the options: for example, since `-recurse` doesn't pass down most options, I personally wouldn't actually use this option in combination with other options (except `-lock` and `-ro`). Similarly, `-classify` is intended for really simple class definitions, and I wouldn't necessarily pass it a data structure like you're doing in your example because the intent is to be able to create more objects of that class with `->new`. On the other hand, what you're doing could be useful in one-time mocks, for example.

Although the way you wrote your example works fine and I don't see anything wrong with it, here's how I personally would have written it:

```perl
h2o -classify => 'My::Class', {}, qw/ foo baz deep /;
h2o -classify => 'My::Class::Details', {}, qw/ a b /;
my $x = My::Class->new( foo=>'bar', baz=>'herp',
	deep=>My::Class::Details->new( a=>1, b=>2 ) );
```

The [Moo](https://metacpan.org/pod/Moo) version is pretty simple too:

```perl
package My::Class {
	use Moo;
	use namespace::clean; # optional but recommended
	has foo  => (is=>'rw');
	has baz  => (is=>'rw');
	has deep => (is=>'rw');
}
package My::Class::Details {
	use Moo;
	use namespace::clean;
	has a => (is=>'rw');
	has b => (is=>'rw');
}
my $x = My::Class->new( foo=>'bar', baz=>'herp',
	deep=>My::Class::Details->new( a=>1, b=>2 ) );
```

That also gives you the power to code defensively and change `'rw'` to `'ro'` where desired and to add things like type checks, for example:

```perl
	use Scalar::Util 'blessed';
	has deep => (is=>'rw', isa=>sub{ die "Isn't My::Class::Details"
		unless blessed($_[0]) && $_[0]->isa('My::Class::Details') });
```

Or, even nicer using [Type::Tiny](https://metacpan.org/pod/Type::Tiny):

```perl
	use Types::Standard qw/ InstanceOf /;
	has deep => (is=>'rw', isa=>InstanceOf['My::Class::Details'] );
```

I'll leave the issue open for a bit and think about this some more, but at the moment I believe trying to make `-recurse` more flexible would result in a complex and confusing configuration that goes against the simplicity the module is trying to provide.

**Comment by oodler577** [comment]
Thank you for the thoughtful reply, this definitely helps me see a greater breadth. This also helps me look at how to use this effectively on larger scale things. I see `h2o` as coming from another angle, typically that of existing scripts with hashrefs that would be improved if accessors were available easily, even at the top level. So it's perfect for "cleaning up" existing code that has a lot of hashref key derefs (e.g., `->{someKey}`). Anyway, thanks again for the reply and this module.

**Comment by haukex** [comment]
> I see `h2o` as coming from another angle, typically that of existing scripts with hashrefs that would be improved if accessors were available easily, even at the top level. So it's perfect for "cleaning up" existing code that has a lot of hashref key derefs (e.g., `->{someKey}`).

Yes, that's exactly what `-recurse` is meant for. If no other code is going to be checking what the classes of those objects are, then there isn't a technical need to assign "nice" class names to those objects, except maybe for your own debugging - but for debugging there are other tricks you can do, for example:

```perl
use warnings;
use strict;
use Util::H2O;
use Data::Dump qw/ dd pp /;
use Data::Dump::Filtered qw/add_dump_filter/;

my $x = { foo => 'bar', baz => 'herp', deep => { a => 1, b => 2 } };
h2o -recurse, $x;

dd $x;

add_dump_filter( sub {
	my ($ctx, $obj) = @_;
	return { dump => 'h2o '.pp({%$obj}) } if $ctx->class=~/^Util::H2O::/;
	# alternative that just prefixes the objects with a comment:
	#return { bless=>'', comment=>'h2o' } if $ctx->class=~/^Util::H2O::/;
	return undef; # normal Data::Dump processing for all other objects
});

print "# with filter:\n";
dd $x;
```

which outputs:

```perl
bless({
  baz  => "herp",
  deep => bless({ a => 1, b => 2 }, "Util::H2O::_556fba0434a9"),
  foo  => "bar",
}, "Util::H2O::_556fba064fe1")
# with filter:
h2o { baz => "herp", deep => h2o { a => 1, b => 2 }, foo => "bar" }
```

which shows that with this filter, you'll get a nicer output of `Util::H2O` objects, while still being valid Perl. Note that options aren't preserved, but debugging output is not usually meant to be entirely roundtrip-able. You can place the `add_dump_filter` call directly under the imports and it'll affect the whole program.
