### ISSUE TITLE
ability for `h2o` to `-alter` an already blessed reference?

### ISSUE THREAD

**Issue by oodler577** [haukex/Util-H2O#4]
I can only describe my situation, and maybe you can offer a suggestiong.

I use `Config::Tiny` a lot, and this creates a blessed reference of the aforementioned type. However, it's a pretty simplistic reference, offering no accessor.

Say I have a config,

```
[database]
db=mydb
host=localhost
port=3306
pw=luggage1234
```

I want to use `Util::H2O::h2o` to create accessors, otherwise the values must be referenced using the traditional deref syntax (e.g., `my $db = $config->{database}->{db}`).

I find myself wanting to do the following, keeping in mind that the primary `$config` reference comes blessed as `Config::Tiny`.

```
my $config = Config::Tiny->read(q{/path/to/my/config.ini});
h2o $config->{database};
# my $db = $config->database->db; # want to do, but can't
my $db = $config->{database}->db; # what I have to do, but isn't quite what I want
```

Considering that `$config` is already a blessed references of `Config::Tiny`, is there an optional way that `h2o` can take an already blessed reference and add an accessor? I know how to do that in normal _Perl_ but I am tempted to think `h2o` can help here. E.g.,

```
# in 2 steps
h2o -alter, $config, qw/database/;
h2o $config->database;
my $db = $config->database->db;
...
```

I don't know how to say to do this in one step, the semantics of `h2o` may not provide for this kind of flexibility - and may also not wish to breach this additinal complexity.

Any thoughts? I hope my description above shows what "use case" I am running up against. Thanks!

**Comment by oodler577** [comment]
Additional comment - this seems like a case of precision _monkey patching_ - so maybe `-patch` is in order; then that. leads me to wonder if `h2o` can provide some operations meant to precisely patch/alter existing references _in flight_ ~ seems like a much better approach than, say, creating a subclass of `Config::Tiny` (in this example) or messing with type globs to add or redefine a method.

**Comment by haukex** [comment]
> Considering that `$config` is already a blessed references of `Config::Tiny`, is there an optional way that `h2o` can take an already blessed reference and add an accessor? ... this seems like a case of precision *monkey patching*

The issue with this is that `Util::H2O` would need to put methods into the `Config::Tiny` package, potentially overwriting exiting methods there and/or causing lots of confusion in other code, since this change would be global. Instead, re-blessing it into a `Util::H2O::*` object would be better, which the module currently doesn't support because it rejects already blessed references. Although it is in theory a feature I could add, what you can currently already do is make a shallow copy:

```perl
my $ct = Config::Tiny->read("foo.ini");
my $config = h2o -recurse, {%$ct};
# OR
my $config = h2o -recurse, {%{ Config::Tiny->read("foo.ini") }};
# OR, on Perl 5.24 and up; 5.20/5.22 need a use feature 'postderef';
my $config = h2o -recurse, { Config::Tiny->read("foo.ini")->%* };
```

Each of these will let you write `$config->database->db` afterwards.

You do lose the ability to say `$config->write` through this, but there are a couple of workarounds:

1. You can do `Config::Tiny::write_string($config)` to get the config as a string, though this solution is a bit hackish since it depends on the current internals of the module (e.g. `::write($config, "bar.ini")` doesn't work).
2. You can make another shallow copy of the object and `bless` that, as in: `bless({%$config},"Config::Tiny")->write("bar.ini")` - but since this bypasses any checks the constructor might do, although there currently aren't any, this breaks encapsulation.
3. If you used the `-nolock` option, you can re-`bless` the object directly, i.e. `bless($config,"Config::Tiny")` instead of the above. This does have the disadvantage of changing the object back to a `Config::Tiny` object, and the same caveat as above applies.
4. I have opened ronsavage/Config-Tiny#4 which, if you used the `-nolock` option, would allow you to do `Config::Tiny->new($config)` to re-bless the object (or without `-nolock`, bless a shallow copy) in a more encapsulated way. So you might want to wait and see if this PR gets accepted.

I'll also consider adding an option maybe named `-force` that would allow already `bless`ed hashrefs to be re-`bless`ed.

**Comment by oodler577** [comment]
Thank you for the informed reply, as always. I also appreciate the example work-arounds. `h2o` is getting close to replacing `bless` altogether for me, so I pretty much see it as a _better_ `bless`. I'm also tempted to want to use `h2o` as a way to do surgery on blessed references. So I don't know if this just means that a more specified tool for doing things to already blessed references is needed. I know there are other modules out there, but none that I know in the same spirit of `h2o`. I think this tool stands alone in its efficacy.

The main use case that I find handy is just making an unblessed hashref into an object with accessors. When using it with the `Config::Tiny` object, I had forgotten that it returned a blessed ref; but it's insufficient for how I want to use it, hence my attempt to use `h2o` with it; the temptation is even created given that it's a nested structure. Anyway, thanks for the reply and your responsiveness.

**Comment by haukex** [comment]
I even went as far as implementing this (c2d2d77eb080141f7d05cd7d31b279e9e3b0bbd7 in the `force_opt` branch), until that implementation made me realize that re-`bless`ing objects is actually not a great idea because it causes the `DESTROY`s of the original class to not be called, which in the case of `h2o` can cause a memory leak because the packages aren't cleaned up, and unknown consequences for other classes. So I ended up deciding that didn't want to encourage this usage.

Instead, I added an example to the documentation for how to use shallow copies to accomplish the same thing. And ronsavage/Config-Tiny#4 has now been merged and released, which makes the whole thing pretty easy. Since it wouldn't be advisable to use this module on hashes with a huge number of keys anyway, I don't think the slightly increased memory usage caused by shallow copies is an issue.
