### ISSUE TITLE
compelling use for replacing `bless` in traditional OOP idiom, but warns about `redefined` method errors...

### ISSUE THREAD

**Issue by oodler577** [haukex/Util-H2O#6]
I want to be able to use `h2o` as `bless` + _other goodies_ ~ here's an issue that, if addressed, could really make `h2o` kick butt for this kind of "edge case". This might be related to #4 (`-alter`) some what, given it's clashing with namespaces and methods therein. But it might also be something altogether different. In any case, this should be a natural way to use `h2o`.

```
package MyClass::Test1;

use Util::H2O qw/h2o/;

sub new {
    my $pkg  = shift;
    my %self = @_;
    my $self = h2o -meth, -class => $pkg, \%self, qw/field1 field2 field3/;
    return $self;
}

sub farp { 
    print qq{faaaaarp!\n};
    return;
}

sub toot {
    print qq{toot!\n};
    return;
}

1;
```

test.pl

```
use strict;
use warnings;

use MyClass::Test1;
    
my $test = MyClass::Test1->new( field0 => 0, field1 => 1, field4 => 4 );
my $test2 = MyClass::Test1->new( field0 => 0, field1 => 1, field4 => 4);
```

result

```
$ perl -I./lib ./t/01-basic.t 
Subroutine MyClass::Test1::field2 redefined at /path/perl5/perlbrew/perls/perl-5.32.0/lib/site_perl/5.32.0/Util/H2O.pm line 323.
Subroutine MyClass::Test1::field4 redefined at /path/perl5/perlbrew/perls/perl-5.32.0/lib/site_perl/5.32.0/Util/H2O.pm line 323.
Subroutine MyClass::Test1::field0 redefined at /path/perl5/perlbrew/perls/perl-5.32.0/lib/site_perl/5.32.0/Util/H2O.pm line 323.
Subroutine MyClass::Test1::field1 redefined at /path/perl5/perlbrew/perls/perl-5.32.0/lib/site_perl/5.32.0/Util/H2O.pm line 323.
Subroutine MyClass::Test1::field3 redefined at /path/perl5/perlbrew/perls/perl-5.32.0/lib/site_perl/5.32.0/Util/H2O.pm line 323.
```

**Comment by oodler577** [comment]
Basically, I want to be able to tell `h2o` to not redefine methods if __PACKAGE_ already exists; possible complication is that since `h2o` is manufacturing __PACKAGE__ and methods so easily; it might be tempting to remove already created accessors. FWIW, I found this when heading towards testing the use of `h2o` for sub-classes, but didn't even get that far.

**Comment by haukex** [comment]
On this one I do unfortunately have to say that I think you're misunderstanding the module a bit, and it might stem from what you wrote in #5 about "replacing" `bless`: *every* call to `h2o` causes methods to be installed in a package/class (hence your `redefined` warnings) - whether that is a new, dynamically generated package in the `Util::H2O::` namespace, or, with the `-class` or `-classify` options, in a user-defined package. In the former case, since the package name is unique to the hashref, clashes don't normally happen unless forced, and in the latter case, clashes are avoided by thinking of the `h2o` call like a package definition, and therefore only making that call *once*. This is also already discussed in the documentation, so I don't think there is anything to fix here.

The mostly-equivalent `h2o` version of the code you showed is:
```perl
use warnings;
use strict;
use Util::H2O;
h2o -classify=>'MyClass::Test1', {
    farp => sub { 
        print qq{faaaaarp!\n};
        return;
    },
    toot => sub {
        print qq{toot!\n};
        return;
    }
}, qw/field1 field2 field3/;
```

To be in line with Perl's package system, you could even place the above code in a file `MyClass/Test1.pm` so you can do a `use MyClass::Test1;` in other code (no `package` needed). (Note: While you *could* do this, I personally wouldn't take the use of the module this far.)

However, if you want to write out your `package` definition like you did above, it doesn't make sense to use `h2o` in `new`. There are *lots* of other class-generation systems out there, just to name one example of many, [perlootut](https://perldoc.perl.org/perlootut) mentions [Class::Tiny](https://metacpan.org/pod/Class::Tiny), which seems to be the kind of thing you're going for in the above code.

**Comment by oodler577** [comment]
Okay, no I get it. I just think it'd behoove your module to admit this use case. It's basically almost there.

**Comment by haukex** [comment]
> I just think it'd behoove your module to admit this use case.

If by that you mean this:

> Basically, I want to be able to tell h2o to not redefine methods if _PACKAGE already exists

Then the issue I see is this: If `h2o` didn't set up methods at all, it wouldn't really be any different from `bless`+`lock_ref_keys`. And having it automatically detect whether methods already exist is fraught with problems: First, AFAIK, detecting whether a package "exists" in Perl isn't that easy, since the internal symbol table is pretty complex and can be modified by all sorts of operations. So, I'd have to try and see if methods already exist. But what if only some of the methods `h2o` wants to set up are already there? How would the module know if the methods already installed are the same or different from the ones it wants to install? And so on.

The use case of defining a class is covered with the `-classify` example that I showed above. It's just written a bit differently from the classic Perl OO type code that you showed in your example, but it is almost completely equivalent, the only difference I see being the treatment of unknown arguments to `new`.

Although it's possible to use `Util::H2O` in the way I showed above, the primary goal of the module is to turn arbitrary hashrefs into objects with accessors for the keys, to prevent typos. That the module can be used to whip up really simple classes is a secondary goal, but the key words here are *whip up really simple* classes - so for example, to dynamically create quick and dirty mock objects for tests and so on. I'd even go so far as to state explicitly that this module is *not* meant to replace OO class definition systems, because that is a topic that gets complex *fast* and is already *extremely* well represented with lots of high-quality modules on the CPAN. This module aims to fill a different niche. I'm happy to add simple features as long as they don't add too much complexity, but at the moment I feel the above would be too complicated.

But perhaps I am misunderstanding the use cases that you mean? More example code is always useful in that regard.

**Comment by haukex** [comment]
Inspired by the discussion here, I've added a small feature to the module in fec84925eb002f4774b0d31504a01b9fb8322dc2 that shortens the code a bit when using `h2o` inside of a `package`.

@oodler577 : Several of my commits have been inspired by your comments, so I'd like to offer to name you in the acknowledgements in the documentation. Please let me know if you would like this and in what form I should credit you, i.e. whether you'd like your full name and/or email given.
