### ISSUE TITLE
feature request: optionally make source hash being `undef` not fatal (pass on `undef`)

### ISSUE THREAD

**Issue by oodler577** [haukex/Util-H2O#8]
Related to #7, the full example I'd like to enable is this; this is 2 of 2 (the first being #7):

I'd like to be able to specify an assignment via external call such that it might be `undef` - e.g., an empty set of database results. Then I'd like to tell `h2o` not to die or even warn; e.g.:

```
  my $h2othing = h2o -undef_ok, external_call_that_could_return_undef();
  if ( defined $h2othing and not $h2othing->exists('someKey') ) {
    die q{Missing 'someKey'!\n};
  }
```

The alternative is the ugly (adding to the "ugly" #7 example),

```
  my $ref = external_call_that_could_return_undef();
  $h2othing = ( $ref ) ? h2o $ref : undef;
  if ( defined $h2othing and not exists $h2othing->{'someKey'} ) {
    die q{Missing 'someKey'!\n};
  }
```

Summary, if the `$ref` being passed to `h2o` for objectification is itself `undef`; I think being able to tell h2o to just give me back `undef` would help eliminate some unnecessary code.

Thanks!

**Comment by haukex** [comment]
I understand the motivation and an `undef` passthrough can be useful in some situations (e.g. Perl's [`length`](https://perldoc.perl.org/functions/length) as of 5.12), and an option like that would be a possibility. OTOH, before adding a new feature, perhaps look at it this way: you're going to have to check for `undef` at some point, either before or after `h2o`. Also, perhaps `my $h2othing = h2o maybe_undef() // {};` could be an alternative? Let me know what you think, whether these alternatives might work.

**Comment by oodler577** [comment]
I need to double check, but I think that `h2o` dies or warns of passed `undef`; the `//` option is a good alternative unless what I want is an actual `undef` - though I admit I don't know off the top of my head if `{}` is strickly identical to `undef` - I'll take a look at this.

**Comment by haukex** [comment]
> I need to double check, but I think that `h2o` dies or warns of passed `undef`

Yes, it requires an unblessed hashref, otherwise it dies.

> the `//` option is a good alternative unless what I want is an actual `undef`

Yes, that's true; the solution you showed with `?:` is an option, of course it's not quite as nice and short - as I commented in #7, you could also consider that if you want to test whether a key exists in the *original* hashref, it would be cleanest/safest to test that original hashref before it goes to `h2o`.

> though I admit I don't know off the top of my head if `{}` is strickly identical to `undef` - I'll take a look at this.

It's not, `{}` is an empty hashref so you'll get an h2o object with no methods (except those inherited from `UNIVERSAL` plus `DESTROY`) and an empty hash behind it. I suggested this because in your example above you were then testing for the existence of keys, a test which would of course then fail. But perhaps the example code is not exactly representative of your actual code, so if you provided a more representative example I could perhaps suggest some more alternatives as well.

I think perhaps a more general solution would be an option `-pass`, which could cause `h2o` to not die when given `undef`, arrayrefs, scalars, objects, etc. - what do you think of this?

**Comment by oodler577** [comment]
> I think perhaps a more general solution would be an option `-pass`, which could cause `h2o` to not die when given `undef`, arrayrefs, scalars, objects, etc. - what do you think of this?

Amazing idea, I like it!

**Comment by oodler577** [comment]
`-safe` might also be a good flag for this, just a though :)
